# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionCable::Channel::TestCase::Behavior`.
# Please instead update this file by running `bin/tapioca dsl ActionCable::Channel::TestCase::Behavior`.


module ActionCable::Channel::TestCase::Behavior
  include GeneratedInstanceMethods

  mixes_in_class_methods ::ActiveSupport::Testing::ConstantLookup::ClassMethods
  mixes_in_class_methods GeneratedClassMethods

  module GeneratedClassMethods
    def _channel_class; end
    def _channel_class=(value); end
    def _channel_class?; end
  end

  module GeneratedInstanceMethods
    def _channel_class; end
    def _channel_class=(value); end
    def _channel_class?; end
  end
end
